export const AUTHSTACK = 'AUTHSTACK';
export const AUTH_LOADING_SCREEN = 'AUTH_LOADING_SCREEN';
export const LOGIN = "LOGIN";
export const BOTTOM_NAVIGATION_STACK = "BOTTOM_NAVIGATION_STACK";
export const HOME_SCREEN_MAIN = 'HOME_SCREEN_MAIN';
export const ADD_CASH_SCREEN = "ADD_CASH_SCREEN";
export const WITHDRAW_SCREEN = "WITHDRAW_SCREEN";
export const PROFILE_SCREEN = "PROFILE_SCREEN";